apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomsqrt-deployment
  labels:
    app: randomsqrt
spec:
  replicas: 3
  selector:
    matchLabels:
      app: randomsqrt
  template:
    metadata:
      labels:
        app: randomsqrt
    spec:
      containers:
      - name: randomsqrt
        image: maximmai/randomsqrt:latest
        resources:
          requests:
            cpu: 100m
        ports:
        - containerPort: 3000